name: Snyk SCA Scan

on:
  push:
    branches: [ "develop" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      contents: read 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Snyk SCA Scanning
      continue-on-error: false
      run: |
        echo "----------Download Latest Snyk CLI-----------"
        curl -Lo ./snyk "https://github.com/snyk/snyk/releases/download/v1.1060.0/snyk-linux"
        chmod +x snyk
        ls -lrt
        echo "----------Authenticating Snyk-----------"
        ./snyk auth ${{secrets.Snyk_token}}
        echo "----------Snyk Scanning-----------"
        echo "----------Snyk Monitor------------"
        ./snyk monitor --all-projects
        snykCount=$(curl -X GET --header 'Content-Type: application/json' --header 'Authorization: token c799f25b-d339-4d15-accd-ae8c11d2c49e' 'https://api.snyk.io/api/v1/org/b75daed6-3330-4723-b097-ed83f67917b4/project/0c204406-4008-493a-9ac9-67eaba4c332f')
             snykCritical=$(echo "$snykCount" | jq .issueCountsBySeverity | .critical )
             snykHigh=$(echo "$snykCount" | jq .issueCountsBySeverity | .high )
             snykMedium=$(echo "$snykCount" | jq .issueCountsBySeverity | .medium )
             snykLow=$(echo "$snykCount" | jq .issueCountsBySeverity | .low )
             echo "CRITICAL = $snykCritical"
             echo "HIGH = $snykHigh"
             echo "HIGH = $snykHigh"
