name: Snyk SCA Scan

on:
  push:
    branches: [ "develop" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      contents: read 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Snyk SCA Scanning
      continue-on-error: false
      run: |
        echo "----------Download Latest Snyk CLI-----------"
        curl -Lo ./snyk "https://github.com/snyk/snyk/releases/download/v1.1060.0/snyk-linux"
        chmod +x snyk
        ls -lrt
        echo "----------Authenticating Snyk-----------"
        ./snyk auth ${{secrets.Snyk_token}}
        echo "----------Snyk Scanning-----------"
        echo "----------Snyk Monitor------------"
        ./snyk monitor --all-projects
        snykCount=$(curl -X GET --header 'Content-Type: application/json' --header 'Authorization: token ${{secrets.Snyk_api_token}}' 'https://api.snyk.io/api/v1/org/3ce8ad2c-4905-476d-a6ca-df1d9605c959/project/49ee4dfc-efb3-4d9c-8e24-17453c1b18ea')
             CRITICAL=$(echo "$snykCount" | jq .issueCountsBySeverity.critical )
             HIGH=$(echo "$snykCount" | jq .issueCountsBySeverity.high )
             MEDIUM=$(echo "$snykCount" | jq .issueCountsBySeverity.medium )
             snykLow=$(echo "$snykCount" | jq .issueCountsBySeverity.low )
             echo "CRITICAL = $CRITICAL"
             echo "HIGH = $HIGH"
             echo "MEDIUM = $MEDIUM"
             echo "LOW = $snykLow"
             if [ $CRITICAL -gt 5 ]
             then
               echo "Failing task because number of critical issues are greater than 5"
               exit 1
             elif [ $HIGH -gt 10 ]
             then
               echo "Failing task because number of high issues are greater than 10"
               exit 1
             elif [ $MEDIUM -gt 30 ]
             then
               echo "Failing task because number of Medium issues are greater than 30"
               exit 1  
             else
               echo "PASSED"
             fi
             
